### ISSUE TITLE
Installation guide for the newbs

### ISSUE THREAD

**Issue by aleclarson** [arjunblj/revert-github-ui#1]
How does one install this puppy?

**Comment by arjunblj** [comment]
1. `git clone` or download.
2. Go to `chrome://extensions/`
3.  Load unpacked extensions
4. Pick directory
5. ???
6. Profit!

**Comment by aleclarson** [comment]
Looks like there's a repo with a pre-packed extension: https://github.com/DennisSnijder/MakeGithubGreatAgain
